name: PHPStan
on: [pull_request]
jobs:
  code_analysis:
    name: Debug
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{fromJson(github)}}
